'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { RequireAuth } from '@/components/require-auth';
import {
  PageBody,
  PageHeader,
  Card,
  CardHeader,
  Badge,
  Metric,
  EmptyState,
  ErrorState,
  LoadingState,
  Select,
} from '@/components/ui/primitives';
import { Button } from '@/components/ui/button';
import { apiClient, type InboundCallDto } from '@/lib/api-client';

/**
 * Inbound traffic.
 *
 * `/integrations` answers "what does METIS call out to". This answers the other
 * half — what called in, with what, and what went back. The two were never the
 * same question, and only one of them had a page.
 *
 * The immediate reason it exists: a partner storefront posting decisions had no
 * way to demonstrate it was talking to METIS at all. Offers that legitimately
 * do not change look identical to offers that are hardcoded, and the only way
 * to tell them apart was to open devtools on somebody else's machine. A call
 * that shows its request, its response and its decision id settles it.
 */

const REFRESH_MS = 2000;

/** Status bands, not exact codes: the reader is scanning for the red row. */
function statusTone(status: number): 'pass' | 'hold' | 'block' | 'neutral' {
  if (status >= 500) return 'block';
  if (status >= 400) return 'hold';
  if (status >= 200 && status < 300) return 'pass';
  return 'neutral';
}

const ORIGIN_LABEL: Record<InboundCallDto['origin'], string> = {
  storefront: 'Storefront',
  console: 'Console',
  unknown: 'Direct',
};

function bytes(n: number): string {
  if (n < 1024) return `${n} B`;
  return `${(n / 1024).toFixed(1)} kB`;
}

function time(iso: string): string {
  const d = new Date(iso);
  return `${d.toLocaleTimeString('en-GB', { hour12: false })}.${String(d.getMilliseconds()).padStart(3, '0')}`;
}

/**
 * One side of a call, rendered.
 *
 * `JSON.stringify(_, null, 2)` rather than a collapsible tree: these payloads
 * are tens of lines, the reader is usually looking for one field, and a tree
 * that has to be opened node by node is slower than scanning indented text.
 */
function Body({ label, body }: { label: string; body: InboundCallDto['request'] }) {
  if (!body) {
    return (
      <div>
        <div className="text-label font-medium text-content-subtle">{label}</div>
        <p className="mt-1 text-label text-content-muted">No body.</p>
      </div>
    );
  }

  const text = body.json !== null && body.json !== undefined
    ? JSON.stringify(body.json, null, 2)
    : (body.text ?? '');

  return (
    <div className="min-w-0">
      <div className="flex items-baseline gap-2">
        <span className="text-label font-medium text-content-subtle">{label}</span>
        <span className="text-label text-content-muted">{bytes(body.bytes)}</span>
        {body.truncated ? <Badge tone="hold">truncated</Badge> : null}
      </div>
      <pre className="mt-1 max-h-80 overflow-auto rounded border border-border bg-surface-sunken p-2 font-mono text-[0.6875rem] leading-relaxed text-content">
        {text}
      </pre>
    </div>
  );
}

function TrafficView() {
  const queryClient = useQueryClient();
  const [expanded, setExpanded] = useState<string | null>(null);
  const [origin, setOrigin] = useState<'all' | InboundCallDto['origin']>('all');
  const [live, setLive] = useState(true);

  const { data, isLoading, error, refetch } = useQuery({
    queryKey: ['inbound-calls'],
    queryFn: () => apiClient.listInboundCalls(250),
    // Polling, because the traffic is generated by another tab. A page that
    // needed a manual refresh to show a call that already happened would be
    // useless for the thing it is for — watching a site drive METIS live.
    refetchInterval: live ? REFRESH_MS : false,
  });

  const clear = useMutation({
    mutationFn: () => apiClient.clearInboundCalls(),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['inbound-calls'] }),
  });

  if (isLoading) return <LoadingState label="Loading traffic" />;
  if (error) {
    return (
      <ErrorState
        description="Could not load the traffic log."
        onRetry={() => {
          void refetch();
        }}
      />
    );
  }

  const all = data?.calls ?? [];
  const calls = origin === 'all' ? all : all.filter((c) => c.origin === origin);

  // Counted over everything, not the filtered view: these describe the API's
  // health, and a filter that quietly changed the failure count would be a
  // number that means something different depending on a dropdown.
  const failures = all.filter((c) => c.status >= 400).length;
  const decisions = all.filter((c) => c.decisionId).length;
  const slowest = all.reduce((m, c) => Math.max(m, c.durationMs), 0);

  if (data && !data.enabled) {
    return (
      <EmptyState
        title="Recording is switched off"
        description="METIS_CALL_LOG=off is set on the server. Unset it and restart to record traffic."
      />
    );
  }

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <Metric label="Calls recorded" value={String(all.length)} />
        <Metric
          label="Decisions produced"
          value={String(decisions)}
          tone={decisions > 0 ? 'accent' : 'neutral'}
        />
        <Metric
          label="Failed"
          value={String(failures)}
          tone={failures > 0 ? 'block' : 'pass'}
        />
        <Metric label="Slowest" value={`${slowest} ms`} />
      </div>

      <Card>
        <CardHeader
          title="Calls"
          description="Newest first. Bodies are held in memory only, capped at 250 calls, and lost when the server restarts."
          actions={
            <div className="flex items-center gap-2">
              <label className="flex items-center gap-1.5 text-label text-content-subtle">
                <input
                  type="checkbox"
                  checked={live}
                  onChange={(e) => setLive(e.target.checked)}
                  className="accent-accent"
                />
                Live
              </label>
              <Select
                aria-label="Caller"
                value={origin}
                onChange={(e) => setOrigin(e.target.value as typeof origin)}
              >
                <option value="all">Every caller</option>
                <option value="storefront">Storefront</option>
                <option value="console">Console</option>
                <option value="unknown">Direct</option>
              </Select>
              <Button
                variant="secondary"
                onClick={() => clear.mutate()}
                disabled={clear.isPending || all.length === 0}
              >
                Clear log
              </Button>
            </div>
          }
        />

        {calls.length === 0 ? (
          <EmptyState
            title="No calls yet"
            description={
              origin === 'all'
                ? 'Open the storefront and load a page. Its decision requests will appear here as they arrive.'
                : `Nothing from ${ORIGIN_LABEL[origin as InboundCallDto['origin']]} yet.`
            }
          />
        ) : (
          <div className="divide-y divide-border">
            {calls.map((call) => {
              const open = expanded === call.id;
              return (
                <div key={call.id}>
                  <button
                    type="button"
                    onClick={() => setExpanded(open ? null : call.id)}
                    aria-expanded={open}
                    // Named explicitly. The row's content is six columns of
                    // times, codes and paths, and the concatenation a screen
                    // reader would otherwise announce is unusable — this says
                    // what the call was in the order somebody would ask.
                    aria-label={`${call.method} ${call.path} — ${call.status}, ${call.durationMs} ms, from ${ORIGIN_LABEL[call.origin]}`}
                    className="flex w-full items-center gap-3 px-card py-2 text-left hover:bg-surface-sunken focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-accent"
                  >
                    <span className="tnum w-24 shrink-0 font-mono text-label text-content-muted">
                      {time(call.at)}
                    </span>
                    <Badge tone={statusTone(call.status)}>{call.status}</Badge>
                    <span className="w-12 shrink-0 font-mono text-label text-content-subtle">
                      {call.method}
                    </span>
                    <span className="min-w-0 flex-1 truncate font-mono text-label text-content">
                      {call.path}
                      {call.query ? (
                        <span className="text-content-muted">{call.query}</span>
                      ) : null}
                    </span>
                    {call.decisionId ? <Badge tone="accent">decision</Badge> : null}
                    <span className="w-20 shrink-0 text-right text-label text-content-muted">
                      {ORIGIN_LABEL[call.origin]}
                    </span>
                    <span className="tnum w-16 shrink-0 text-right font-mono text-label text-content-subtle">
                      {call.durationMs} ms
                    </span>
                  </button>

                  {open ? (
                    <div className="space-y-3 border-t border-border bg-surface px-card py-3">
                      {call.error ? (
                        <p className="rounded border border-block/40 bg-block-subtle px-2 py-1.5 text-body text-block">
                          {call.error}
                        </p>
                      ) : null}

                      {call.decisionId ? (
                        <p className="text-label text-content-subtle">
                          Produced{' '}
                          <Link
                            href={`/decisions/${call.decisionId}`}
                            className="font-mono text-accent underline underline-offset-2"
                          >
                            {call.decisionId}
                          </Link>{' '}
                          — the trace shows which candidates were considered and why the
                          winner won.
                        </p>
                      ) : null}

                      <div className="grid gap-3 lg:grid-cols-2">
                        <Body label="Request" body={call.request} />
                        <Body label="Response" body={call.response} />
                      </div>
                    </div>
                  ) : null}
                </div>
              );
            })}
          </div>
        )}
      </Card>
    </div>
  );
}

export default function TrafficPage() {
  return (
    <RequireAuth>
      <PageHeader
        title="Inbound traffic"
        description="Every call served by this API, with the request and response in full. The outbound half — what METIS calls out to — is on Integrations."
      />
      <PageBody>
        <TrafficView />
      </PageBody>
    </RequireAuth>
  );
}
